-- Prosec SaaS control plane schema.
-- Portable across H2 (MODE=PostgreSQL) and PostgreSQL.
-- Protobuf messages are the source of truth; each row stores the serialized
-- message in "payload" plus the columns needed for keys, filters and sorting.

CREATE TABLE IF NOT EXISTS tenants (
    id VARCHAR(80) NOT NULL,
    lifecycle VARCHAR(40) NOT NULL,
    payload BYTEA NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sites (
    id VARCHAR(80) NOT NULL,
    tenant_id VARCHAR(80) NOT NULL,
    payload BYTEA NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_sites_tenant ON sites (tenant_id);

CREATE TABLE IF NOT EXISTS global_objects (
    id VARCHAR(80) NOT NULL,
    payload BYTEA NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS object_grants (
    tenant_id VARCHAR(80) NOT NULL,
    object_id VARCHAR(80) NOT NULL,
    payload BYTEA NOT NULL,
    PRIMARY KEY (tenant_id, object_id)
);

CREATE TABLE IF NOT EXISTS container_workloads (
    tenant_id VARCHAR(80) NOT NULL,
    workload_id VARCHAR(160) NOT NULL,
    site_id VARCHAR(80) NOT NULL,
    namespace VARCHAR(255) NOT NULL,
    pod_name VARCHAR(255) NOT NULL,
    container_name VARCHAR(255) NOT NULL,
    payload BYTEA NOT NULL,
    PRIMARY KEY (tenant_id, workload_id)
);

CREATE INDEX IF NOT EXISTS idx_workloads_tenant_site ON container_workloads (tenant_id, site_id);

CREATE INDEX IF NOT EXISTS idx_workloads_tenant_namespace ON container_workloads (tenant_id, namespace);

CREATE TABLE IF NOT EXISTS site_credentials (
    site_id VARCHAR(80) NOT NULL,
    tenant_id VARCHAR(80) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    issued_at_epoch_ms BIGINT NOT NULL,
    PRIMARY KEY (site_id)
);

CREATE TABLE IF NOT EXISTS global_object_versions (
    object_id VARCHAR(80) NOT NULL,
    version BIGINT NOT NULL,
    payload BYTEA NOT NULL,
    PRIMARY KEY (object_id, version)
);

CREATE TABLE IF NOT EXISTS event_log (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id VARCHAR(80) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    payload BYTEA NOT NULL,
    PRIMARY KEY (seq)
);

CREATE INDEX IF NOT EXISTS idx_event_log_tenant ON event_log (tenant_id, seq);

CREATE INDEX IF NOT EXISTS idx_event_log_type ON event_log (event_type, seq);
